### ISSUE TITLE
Provide example configuration from demo?

### ISSUE THREAD

**Issue by ElPiloto** [whleucka/reverb.nvim#2]
Hello, this is a really fun plugin! Is it possible to provide the example configuration and sounds used in the demo? I know you explicitly chose not to package any sounds in this repo, but could you give an example of the demo configuration? Thanks!

**Comment by whleucka** [comment]
Hi there!
I can do that for you. I will update the README later tonight, thanks!

**Comment by whleucka** [comment]
Sorry for the delay.

I think the example in the README shows the correct configuration for the demo.

Here are the steps:
- Download [kenney_interface-sounds.zip](https://www.kenney.nl/assets/interface-sounds)
  - Find sounds that you like and move them to a local directory
- Update the reverb.nvim config:
  - Add hooks to events where you want to hear a sound
    - Provide path to sound file
    - Set target volume level (0-100)

The full example would look something like this:

```lua
local sound_dir = "/home/directory/path/sounds/"
{
  "whleucka/reverb.nvim",
  event = "BufReadPre",
  opts = {
    sounds = {
      BufRead = { path = sound_dir .. "start.ogg", volume = 100 },
      CursorMovedI = { path = sound_dir .. "click.ogg", volume = 100 },
      InsertLeave = { path = sound_dir .. "toggle.ogg", volume = 100 },
      ExitPre = { path = sound_dir .. "exit.ogg", volume = 100 },
      BufWrite = { path = sound_dir .. "save.ogg", volume = 100 },
    },
  },
}
```
