### ISSUE TITLE
'reverb.nvim does ship with any sounds'

### ISSUE THREAD

**Issue by Kamilcuk** [whleucka/reverb.nvim#3]
The readme states that reverb does ship with any sounds. But there are no sounds. Soo which one is it?

Would it be possible to include default sounds with the plugin?

**Comment by whleucka** [comment]
Sorry if there was some confusion on my part. I meant to say: does *not* ship with any sounds. 

I provided a link to some interface sounds that you can find here: https://www.kenney.nl/assets/interface-sounds.
